package server.cotroller;

import server.model.Database;
import server.model.Question;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class Server implements Runnable {

    @Override
    public void run() {
        initDatabase();
        ExecutorService executorService = Executors.newCachedThreadPool();
        new Thread(new RandomHandler()).start();
        while (true) {
            try (ServerSocket serverSocket = new ServerSocket(80)){
                Socket socket = serverSocket.accept();
                executorService.execute(new ServerRunner(socket));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }

    private void initDatabase() {
        ArrayList<String> test = new ArrayList<>();
        test.add("چین");
        test.add("امریکا");
        test.add("روسیه");
        test.add("هند");
        Database.addQuestion(new Question("SPORT", "بیشترین مدال طلا المپیک ۲۰۲۲", test, test.get(0)));
        test = new ArrayList<>();
        test.add("لوپز");
        test.add("رضازاده");
        test.add("فلیپس");
        test.add("هانگ ژو");
        Database.addQuestion(new Question("SPORT", "پرافتخارترین مدال آور المپیک", test, test.get(2)));
        test = new ArrayList<>();
        test.add("کیمیا علیزاده");
        test.add("هانیه رستمیان");
        test.add("معصومه جعفری");
        test.add("سیما تیرانداز");
        Database.addQuestion(new Question("SPORT", "اولین مدال آور زنان ایران در المپیک", test, test.get(0)));
        test = new ArrayList<>();
        test.add("امباپه");
        test.add("مسی");
        test.add("رونالدو");
        test.add("مودریچ");
        Database.addQuestion(new Question("FOOTBALL", "آقای گل جام جهانی قطر", test, test.get(0)));
        test = new ArrayList<>();
        test.add("هری کین");
        test.add("امباپه");
        test.add("رونالدو");
        test.add("مودریچ");
        Database.addQuestion(new Question("FOOTBALL", "آقای گل جام جهانی ۲۰۱۸", test, test.get(0)));
        test = new ArrayList<>();
        test.add("برزیل");
        test.add("فرانسه");
        test.add("ایتالیا");
        test.add("آلمان");
        Database.addQuestion(new Question("FOOTBALL", "قهرمان جام جهانی ۱۹۹۴", test, test.get(0)));
        test = new ArrayList<>();
        test.add("هیدروژن");
        test.add("هلیم");
        test.add("لیتیم");
        test.add("بریلیم");
        Database.addQuestion(new Question("SCIENCE", "اولین عنصر جدول تناوبی", test, test.get(0)));
        test = new ArrayList<>();
        test.add("منیزم");
        test.add("گوگرد");
        test.add("کلر");
        test.add("آرگون");
        Database.addQuestion(new Question("SCIENCE", "کدام عنصر با اکسبژن ترکیب یونی میدهد", test, test.get(0)));
        test = new ArrayList<>();
        test.add("پاسکال");
        test.add("جاوا");
        test.add("سی شارپ");
        test.add("سی پلاس پلاس");
        Database.addQuestion(new Question("SCIENCE", "کدام زبان برنامه نویسی شی گرا نیست؟", test, test.get(0)));
        test = new ArrayList<>();
        test.add("علی");
        test.add("حسن");
        test.add("حسین");
        test.add("محمد");
        Database.addQuestion(new Question("RELIGIOUS", "اولین امام شیعیان", test, test.get(0)));
        test = new ArrayList<>();
        test.add("۱۱۴");
        test.add("۱۱۰");
        test.add("۱۰۰");
        test.add("۱۲۴");
        Database.addQuestion(new Question("RELIGIOUS", "قران چند سوره دارد", test, test.get(0)));
        test = new ArrayList<>();
        test.add("بقره");
        test.add("ظلمات");
        test.add("عامرون");
        test.add("الزلزال");
        Database.addQuestion(new Question("RELIGIOUS", "بلند ترین سوره قرآن", test, test.get(0)));
        test = new ArrayList<>();
        test.add("پکن");
        test.add("توکیو");
        test.add("گوانژو");
        test.add("جاکارتا");
        Database.addQuestion(new Question("PUBLIC_INFORMATION", "پایتخت کشور چین", test, test.get(0)));
        test = new ArrayList<>();
        test.add("اروپا");
        test.add("اسیا");
        test.add("اقیانوسیه");
        test.add("امریکا");
        Database.addQuestion(new Question("PUBLIC_INFORMATION", "آلمان در چه قاره ایی هست", test, test.get(0)));
        test = new ArrayList<>();
        test.add("روسیه");
        test.add("چین");
        test.add("هند");
        test.add("امریکا");
        Database.addQuestion(new Question("PUBLIC_INFORMATION", "بزرگترین کشور جهان", test, test.get(0)));
        test = new ArrayList<>();
        test.add("گیلان");
        test.add("گلستان");
        test.add("مازندران");
        test.add("اردبیل");
        Database.addQuestion(new Question("GEOGRAPHY", "شهر شفت در چه استانی هست", test, test.get(0)));
        test = new ArrayList<>();
        test.add("فارس");
        test.add("تهران");
        test.add("اصفهان");
        test.add("خراسان شمالی");
        Database.addQuestion(new Question("GEOGRAPHY", "بزرگترین استان ایران", test, test.get(0)));
        test = new ArrayList<>();
        test.add("کرمان");
        test.add("فارس");
        test.add("خوزستان");
        test.add("لرستان");
        Database.addQuestion(new Question("GEOGRAPHY", "ارگ بم در کدام استان است", test, test.get(0)));
        test = new ArrayList<>();
        test.add("اصفهان");
        test.add("تهران");
        test.add("تبریز");
        test.add("قزوین");
        Database.addQuestion(new Question("HISTORY", "پایتخت ایران در دوران صفویه", test, test.get(0)));
        test = new ArrayList<>();
        test.add("سلظان حسین");
        test.add("شاه عباس دوم");
        test.add("نادر شاه");
        test.add("شاه اسماعیل");
        Database.addQuestion(new Question("HISTORY", "اخرین پادشاه صفویه", test, test.get(0)));
        test = new ArrayList<>();
        test.add("۵۹");
        test.add("۵۸");
        test.add("۵۷");
        test.add("۶۰");
        Database.addQuestion(new Question("HISTORY", "جنگ ایران و عراق در چه سالی شروع شد", test, test.get(0)));
        test = new ArrayList<>();
        test.add("۳۵۸۰۲");
        test.add("۳۴۷۰۲");
        test.add("۳۵۸۱۲");
        test.add("۲۳۷۱۲");
        Database.addQuestion(new Question("MATH", "۱۵۳ * ۲۳۴", test, test.get(0)));
        test = new ArrayList<>();
        test.add("۴۳");
        test.add("۴۰");
        test.add("۶۱");
        test.add("۱۹");
        Database.addQuestion(new Question("MATH", "۳ *(۲ + ۳ * ۴) + ۱", test, test.get(0)));
        test = new ArrayList<>();
        test.add("۱۰");
        test.add("۲۰");
        test.add("۳۰");
        test.add("۴۰");
        Database.addQuestion(new Question("MATH", "۱/۴ * ۴۰", test, test.get(0)));
        test = new ArrayList<>();
        test.add("تاریخ");
        test.add("کشور");
        test.add("قاره");
        test.add("شهر");
        Database.addQuestion(new Question("ENGLISH", "mean History", test, test.get(0)));
        test = new ArrayList<>();
        test.add("شیوه");
        test.add("زاه رفتن");
        test.add("خندیدن");
        test.add("خوبی");
        Database.addQuestion(new Question("ENGLISH", "mean method", test, test.get(0)));
        test = new ArrayList<>();
        test.add("پیشرفته");
        test.add("سطحی");
        test.add("اولیه");
        test.add("پایانی");
        Database.addQuestion(new Question("ENGLISH", "mean advanced", test, test.get(0)));
        test = new ArrayList<>();
        test.add("جاوا");
        test.add("پابتون");
        test.add("سی شارپ");
        test.add("سی پلاس پلاس");
        Database.addQuestion(new Question("TECHNOLOGY", "کدام زبان برنامه نویسی جوان تر است", test, test.get(0)));
        test = new ArrayList<>();
        test.add("جاوا");
        test.add("جاوا اسکریپت");
        test.add("پایتون");
        test.add("سی شارپ");
        Database.addQuestion(new Question("TECHNOLOGY", "اف ایکس کتابخانه کدام زبان است", test, test.get(0)));
        test = new ArrayList<>();
        test.add("نود جی اس");
        test.add("دات نت کور");
        test.add("جنگو");
        test.add("اسپرینگ");
        Database.addQuestion(new Question("TECHNOLOGY", "محبوب ترین فریم ورک بک اند", test, test.get(0)));
        test = new ArrayList<>();
        test.add("نولان");
        test.add("وینس گیلیگان");
        test.add("اصغر فرهادی");
        test.add("مرلین مونرو");
        Database.addQuestion(new Question("CINEMA", "کارگردان اوپنهایمر", test, test.get(0)));
        test = new ArrayList<>();
        test.add("سعید روستایی");
        test.add("حسن فتحی");
        test.add("رامبد جوان");
        test.add("اصغر فرهادی");
        Database.addQuestion(new Question("CINEMA", "کارگردان برادران لیلا", test, test.get(0)));
        test = new ArrayList<>();
        test.add("پریناز ایزدیار");
        test.add("ترانه علیدوستی");
        test.add("نوید محمدزاده");
        test.add("فرهاد اصلانی");
        Database.addQuestion(new Question("CINEMA", "کدام بازیگر در برادران لیلا ایفای نقش نکرده است", test, test.get(0)));
        test = new ArrayList<>();
        test.add("محسن یگانه");
        test.add("مرتضی پاشیایی");
        test.add("مجسن چاووشی");
        test.add("علی زندوکیلی");
        Database.addQuestion(new Question("MUSIC", "خواننده آهنگ بهت قول میدم کیست", test, test.get(0)));
        test = new ArrayList<>();
        test.add("سروش لشکری");
        test.add("یاسر بختیاری");
        test.add("رضا انصاری");
        test.add("امیر تتلو");
        Database.addQuestion(new Question("MUSIC", "پدر رپ فارسی", test, test.get(0)));
        test = new ArrayList<>();
        test.add("رضا پیشرو");
        test.add("هیچکس");
        test.add("یاس");
        test.add("مهراد هیدن");
        Database.addQuestion(new Question("MUSIC", "آهنگ قبرستان هیپ هاپ اثر کیست", test, test.get(0)));
    }
}
